version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.4
    - 3.6.6
    - 3.6.9
  - dependency-name: karma
    versions:
    - 5.2.3
    - 6.1.1
    - 6.1.2
    - 6.3.0
    - 6.3.1
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 4.2.2
  - dependency-name: karma-typescript
    versions:
    - 5.3.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
